### ISSUE TITLE
Passing only Threshold amount of Trustees causes crash

### ISSUE THREAD

**Issue by keithrfung** [microsoft/ElectionGuard-SDK-C-Implementation#58]
## Bug Report

**Current Behavior**
If only the threshold amount of trustees is passed in, application crashes. 

The call to the `tallyvotes` method needs to send over all the trusteeKeys in the 2nd parameter (not just the ones that are present) and the 3rd parameter represents the number of trustees that are actually present for the decryption. (w/ threshold already set in the api config sent in the 1st parameter) So with this set up, the an API will have to do the actual validation that the number of trustees announced has reached the appropriate threshold number before calling the TallyVotes method

**Expected behavior/code**
Only the threshold amount of trustees should be necessary for encryption and application should not crash.

**Comment by pamtaro** [comment]
Currently, the call to the `TallyVotes` API method needs to send over _all_ the trusteeKeys in the 2nd parameter (not just the ones that are present) and the 3rd parameter represents the number of trustees that are _actually_ present for the decryption (w/ threshold set in the api config sent in the 1st parameter).

It is possible that we might not need _all_ the trustees to perform the decryption. We can confirm this by making the following changes to the API code (and updating the corresponding API example):

- During initialization of the trustees array, instead of using the `api_config.num_trustees` in the loop to create the decryption trustees array, use the `num_decrypting_trustees` param from the API call: https://github.com/microsoft/ElectionGuard-SDK-C-Implementation/blob/master/src/electionguard/api/tally_votes.c#L137

- During the tally step, also update the loop to use the `num_decrypting_trustees` instead of the `api_config.num_trustees`: https://github.com/microsoft/ElectionGuard-SDK-C-Implementation/blob/master/src/electionguard/api/tally_votes.c#L158

- Some additional logic will also need to be added to match up the index of the present trustees to the index of the `requests_present` array that's returned from the `Decryption_Coordinator_all_shares_received`: https://github.com/microsoft/ElectionGuard-SDK-C-Implementation/blob/master/src/electionguard/api/tally_votes.c#L230

- And update the cleanup loop through trustees to use the `num_decrypting_trustees` instead of the `api_config.num_trustees`: https://github.com/microsoft/ElectionGuard-SDK-C-Implementation/blob/master/src/electionguard/api/tally_votes.c#L94
